services:
  mysql:
    image: mysql:8.0
    restart: always
    command:
      - --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: aqua8282
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

networks:
  default:
    name: aqua-be
