CREATE TABLE `GROUP_CODE` (
    `GROUP_CODE_ID` VARCHAR(20) NOT NULL COMMENT '그룹코드',
    `GROUP_CODE_NAME` VARCHAR(30) COMMENT '그룹코드명',
    `created_by` INT NOT NULL DEFAULT '-1' COMMENT '최초생성자',
    `created_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초생성일시',
    `updated_by` INT NOT NULL DEFAULT '-1' COMMENT '최종수정자',
    `updated_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종수정일시',
    PRIMARY KEY (`GROUP_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='그룹코드';


CREATE TABLE `COMMON_CODE` (
    `COMMON_CODE_ID` VARCHAR(20) NOT NULL COMMENT '공통코드',
    `GROUP_CODE_ID` VARCHAR(20) NOT NULL COMMENT '그룹코드',
    `COMMON_CODE_NAME` VARCHAR(30) COMMENT '코드명',
    `created_by` INT NOT NULL DEFAULT '-1' COMMENT '최초생성자',
    `created_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초생성일시',
    `updated_by` INT NOT NULL DEFAULT '-1' COMMENT '최종수정자',
    `updated_datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '최종수정일시',
    PRIMARY KEY (`COMMON_CODE_ID`,`GROUP_CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='공통코드';
